대운 11월 3주차
Team-Astronauts/programmers-LvUpStudy pull request #42
Opened 2022-11-14 08:15 UTC by Ocknyer

2022-11-15 07:30 UTC, yjlee9909 commented on daeun/lv1/두-정수-사이의-합.js
> +}
와!!! 저도 어떤 방법으로 풀어야 좀 더 간단하게 풀 수 있을까 고민을 해봤는데 
가우스 공식은 진짜 생각도 못해봤네요!!
```suggestion
function solution(a, b){
    return (a+b)*(Math.abs(b-a)+1)/2; // 가우스 공식
}
```
좋은 코드 공유 감사합니다!! 👍

2022-11-15 07:46 UTC, Han-Sang commented on daeun/lv1/두-정수-사이의-합.js
> +}
오.. 가우스 공식 방법이 있었군요 저도 생각 치 못해봤습니다. 코드 잘보았습니다!

2022-11-15 12:47 UTC, heejiyang commented on daeun/lv1/두-정수-사이의-합.js
> +}
```suggestion
function solution(a, b){
    return (a+b)*(Math.abs(b-a)+1)/2; // 가우스 공식
}
```
와우...가우스 공식을 떠올리지 못했습니다! 대운님 코드 잘봤습니다!

2022-11-16 08:25 UTC, Ocknyer commented on daeun/lv1/두-정수-사이의-합.js
> +}
@yjlee9909 @Han-Sang 저도 여러 풀이 방법을 찾아보다, 가우스 공식을 적용해 봤습니다. 비슷한 문제에서 자주 쓰일 수 있는 공식이라, 코드를 외워버리시면 도움이 많이 될 것 같습니다! 😊

2022-11-16 08:26 UTC, Ocknyer commented on daeun/lv1/두-정수-사이의-합.js
> +}
@heejiyang 감사합니다! 상혁님과 유진님께도 말씀드렸듯이, 코드를 외우시면 다른 문제에서도 적용하실 수 있을 듯 합니다! 😃

2022-11-16 09:30 UTC, Han-Sang commented on daeun/lv1/예산.js
>          budget -= sortedD[i]
대운님이 유진님께 말씀한 피드백처럼 원본 배열 바꾸지 않고 효율적으로 하는 방법이 있군요 (+ reduce 방법도 어떻게 풀어야할지 고민하다가 풀지 못했는데 대운님의 풀이로 배우고 갑니다!)

2022-11-16 10:57 UTC, Ocknyer commented on daeun/lv1/예산.js
>          budget -= sortedD[i]
@Han-Sang reduce가 활용 방법이 상당히 많더라구요! 코멘트 감사합니다!!😊

2022-11-16 11:11 UTC, yjlee9909 commented on daeun/lv1/예산.js
> +}
```suggestion
// reduce를 활용한 방법.
function solution2(d, budget) {
    const sortedD = d.sort((a, b) => a - b)
    return sortedD.reduce((acc, cur) => {
        budget -= cur;
         // (budget >= 0)은 budget -= cur의 횟수만큼 그 결과를 true 혹은 false로 반환한다.
         // 예시 1의 경우 true(1)가 세 번, false(0)가 세 번 출력되므로 acc + 3이 결과로 return 된다.
        return acc + (budget >= 0);
    }, 0)
}
```
오!! (budget >= 0)이 true, false로 반환하는 걸 활용해서 사용할 수도 있군요!!
대운님 덕분에 또 새로운 방법을 알아갑니다~!! 😃👍

2022-11-16 18:28 UTC, Ocknyer commented on daeun/lv1/예산.js
> +}
신박한 방법이긴 하지만 저처럼 초보자는 한 눈에 알아보기 쉽지 않았습니다 ㅎㅎ.. 코멘트 감사합니다~!

2022-11-17 08:10 UTC, yjlee9909 commented on daeun/lv1/수박수박수박수박수박수?.js
> +}
```suggestion
function solution(n) {
    return '수박'.repeat(n).slice(0, -n)
}
```
대운님 진짜 코드 간단하게 효율적으로 잘 짜시는 것 같아요!! 👍
맨날 배워만 가는 것 같지만 또 배워 갑니다~~ 🤗

2022-11-17 08:12 UTC, yjlee9909 commented on daeun/lv1/수박수박수박수박수박수?.js
> +}
repeat과 slice 생각해보지도 못한 방법이여서 진짜 너무너무 놀랍네요~ 🤔

2022-11-17 08:12 UTC, Ocknyer commented on daeun/lv1/수박수박수박수박수박수?.js
> +}
@yjlee9909 이래 보여도 항상 처음 풀면 길이가 길답니다 🥲 항상 좋은 말씀 해주셔서 감사합니다!👍

2022-11-17 12:23 UTC, yoyoujin requested changes

2022-11-17 12:23 UTC, yoyoujin commented on daeun/lv1/수박수박수박수박수박수?.js
> +}
오 저도 repeat으로 풀어보고 싶었는데 대운님 코드 잘 보고 갑니다 ~😊

2022-11-19 14:48 UTC, Ocknyer commented on daeun/lv1/수박수박수박수박수박수?.js
> +}
@yoyoujin slice로 잘라야 할 부분을 고민하는 게 좀 걸렸습니다 ㅎㅎ 감사합니다! 👍

2022-11-20 03:01 UTC, merged